version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - git init
      - git add .
      - git config --global user.email "you@example.com"
      - git config --global user.name "Your Name"
      - git commit -m "Initial commit"
  build:
    commands:
      - echo "Starting build phase"
      - git status
      - git log
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  discard-paths: no
