version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - git init  # Initialize git repository
      - git add .  # Add all files
  build:
    commands:
      - echo "Starting build phase"
      - git status  # Now this should work
      - git log  # And this too

artifacts:
  files:
    - '**/*'
